# OCI Resource Manager Stack Schema
# This file defines the UI for Resource Manager stack creation

title: "OCI GenAI Integration Lab Stack"
description: "Deploy a complete RAG solution with OpenSearch, Data Science, and GenAI Agent"
schemaVersion: 1.1.0
version: "1.0.0"
locale: "en"

variableGroups:
  - title: "General Configuration"
    variables:
      - project_name
      - environment
      - compartment_ocid
      - region

  - title: "Network Configuration"
    variables:
      - vcn_cidr_blocks
      - public_subnet_cidr
      - private_subnet_cidr

  - title: "OpenSearch Configuration"
    variables:
      - opensearch_version
      - opensearch_master_node_count
      - opensearch_master_node_ocpu
      - opensearch_master_node_memory
      - opensearch_data_node_count
      - opensearch_data_node_ocpu
      - opensearch_data_node_memory
      - opensearch_data_node_storage
      - opensearch_admin_username
      - opensearch_admin_password

  - title: "Data Science Configuration"
    variables:
      - notebook_shape
      - notebook_ocpus
      - notebook_memory_gb
      - notebook_storage_gb

  - title: "GenAI Configuration"
    variables:
      - genai_model_id
      - genai_embedding_model_id
      - genai_max_tokens
      - genai_temperature

  - title: "Advanced Settings"
    visible: 
      and:
        - show_advanced_options
    variables:
      - chunk_size
      - chunk_overlap
      - batch_size
      - similarity_threshold
      - top_k_results
      - enable_monitoring
      - enable_logging
      - enable_backup

variables:
  # Hidden variables
  tenancy_ocid:
    type: string
    title: "Tenancy OCID"
    description: "The OCID of the tenancy"
    required: true
    visible: false

  user_ocid:
    type: string
    title: "User OCID"
    description: "The OCID of the user"
    required: true
    visible: false

  fingerprint:
    type: string
    title: "API Key Fingerprint"
    description: "The fingerprint of the API key"
    required: true
    visible: false

  private_key_path:
    type: string
    title: "Private Key Path"
    description: "Path to the private key file"
    required: true
    visible: false

  # General Configuration
  project_name:
    type: string
    title: "Project Name"
    description: "Name prefix for all resources"
    default: "oci-genai-lab"
    required: true
    pattern: "^[a-z][a-z0-9-]{0,29}$"

  environment:
    type: enum
    title: "Environment"
    description: "Deployment environment"
    default: "dev"
    required: true
    enum:
      - dev
      - test
      - prod

  compartment_ocid:
    type: oci:identity:compartment:id
    title: "Compartment"
    description: "Compartment for resources"
    required: true

  region:
    type: oci:identity:region:name
    title: "Region"
    description: "Region for deployment (GenAI requires us-chicago-1)"
    default: "us-chicago-1"
    required: true

  # Network Configuration
  vcn_cidr_blocks:
    type: array
    items:
      type: string
    title: "VCN CIDR Blocks"
    description: "CIDR blocks for the VCN"
    default: ["10.0.0.0/16"]
    required: true

  public_subnet_cidr:
    type: string
    title: "Public Subnet CIDR"
    description: "CIDR block for public subnet"
    default: "10.0.1.0/24"
    required: true

  private_subnet_cidr:
    type: string
    title: "Private Subnet CIDR"
    description: "CIDR block for private subnet"
    default: "10.0.2.0/24"
    required: true

  # OpenSearch Configuration
  opensearch_version:
    type: enum
    title: "OpenSearch Version"
    description: "Version of OpenSearch to deploy"
    default: "2.11"
    required: true
    enum:
      - "2.11"
      - "2.9"
      - "2.7"

  opensearch_master_node_count:
    type: integer
    title: "Master Node Count"
    description: "Number of master nodes (1 for dev, 3 for prod)"
    default: 1
    minimum: 1
    maximum: 3

  opensearch_master_node_ocpu:
    type: integer
    title: "Master Node OCPUs"
    description: "OCPUs per master node"
    default: 1
    minimum: 1
    maximum: 8

  opensearch_master_node_memory:
    type: integer
    title: "Master Node Memory (GB)"
    description: "Memory per master node in GB"
    default: 8
    minimum: 8
    maximum: 64

  opensearch_data_node_count:
    type: integer
    title: "Data Node Count"
    description: "Number of data nodes"
    default: 2
    minimum: 1
    maximum: 10

  opensearch_data_node_ocpu:
    type: integer
    title: "Data Node OCPUs"
    description: "OCPUs per data node"
    default: 2
    minimum: 1
    maximum: 16

  opensearch_data_node_memory:
    type: integer
    title: "Data Node Memory (GB)"
    description: "Memory per data node in GB"
    default: 16
    minimum: 8
    maximum: 128

  opensearch_data_node_storage:
    type: integer
    title: "Data Node Storage (GB)"
    description: "Storage per data node in GB"
    default: 50
    minimum: 50
    maximum: 1000

  opensearch_admin_username:
    type: string
    title: "OpenSearch Admin Username"
    description: "Admin username for OpenSearch"
    default: "admin"
    required: true

  opensearch_admin_password:
    type: password
    title: "OpenSearch Admin Password"
    description: "Admin password for OpenSearch (min 8 chars)"
    required: true
    pattern: "^.{8,}$"

  # Data Science Configuration
  notebook_shape:
    type: enum
    title: "Notebook Shape"
    description: "Compute shape for Data Science notebook"
    default: "VM.Standard.E4.Flex"
    required: true
    enum:
      - "VM.Standard.E4.Flex"
      - "VM.Standard.E3.Flex"
      - "VM.Standard3.Flex"
      - "VM.Standard.A1.Flex"

  notebook_ocpus:
    type: integer
    title: "Notebook OCPUs"
    description: "Number of OCPUs for notebook"
    default: 2
    minimum: 1
    maximum: 64

  notebook_memory_gb:
    type: integer
    title: "Notebook Memory (GB)"
    description: "Memory for notebook in GB"
    default: 16
    minimum: 8
    maximum: 256

  notebook_storage_gb:
    type: integer
    title: "Notebook Storage (GB)"
    description: "Block storage size in GB"
    default: 100
    minimum: 50
    maximum: 32768

  # GenAI Configuration
  genai_model_id:
    type: enum
    title: "GenAI Model"
    description: "Model for text generation"
    default: "cohere.command-r-plus"
    required: true
    enum:
      - "cohere.command-r-plus"
      - "cohere.command-r"
      - "meta.llama-3.1-70b-instruct"
      - "meta.llama-3.1-405b-instruct"

  genai_embedding_model_id:
    type: enum
    title: "Embedding Model"
    description: "Model for generating embeddings"
    default: "cohere.embed-english-v3.0"
    required: true
    enum:
      - "cohere.embed-english-v3.0"
      - "cohere.embed-english-light-v3.0"
      - "cohere.embed-multilingual-v3.0"

  genai_max_tokens:
    type: integer
    title: "Max Tokens"
    description: "Maximum tokens for responses"
    default: 2048
    minimum: 256
    maximum: 4096

  genai_temperature:
    type: number
    title: "Temperature"
    description: "Model temperature (0-1)"
    default: 0.7
    minimum: 0
    maximum: 1

  # Advanced Settings
  show_advanced_options:
    type: boolean
    title: "Show Advanced Options"
    description: "Display advanced configuration options"
    default: false

  chunk_size:
    type: integer
    title: "Chunk Size"
    description: "Document chunk size for embeddings"
    default: 1000
    minimum: 100
    maximum: 4000

  chunk_overlap:
    type: integer
    title: "Chunk Overlap"
    description: "Overlap between document chunks"
    default: 200
    minimum: 0
    maximum: 500

  batch_size:
    type: integer
    title: "Batch Size"
    description: "Batch size for processing"
    default: 50
    minimum: 10
    maximum: 200

  similarity_threshold:
    type: number
    title: "Similarity Threshold"
    description: "Threshold for similarity search"
    default: 0.7
    minimum: 0
    maximum: 1

  top_k_results:
    type: integer
    title: "Top K Results"
    description: "Number of results to retrieve"
    default: 5
    minimum: 1
    maximum: 20

  enable_monitoring:
    type: boolean
    title: "Enable Monitoring"
    description: "Enable OCI Monitoring"
    default: true

  enable_logging:
    type: boolean
    title: "Enable Logging"
    description: "Enable OCI Logging"
    default: true

  enable_backup:
    type: boolean
    title: "Enable Backup"
    description: "Enable automated backups"
    default: false

outputs:
  stack_version:
    type: string
    title: "Stack Version"
    displayText: "Stack Version: ${stack_version}"

  opensearch_endpoint:
    type: string
    title: "OpenSearch Endpoint"
    displayText: "OpenSearch Endpoint: ${opensearch_endpoint}"

  notebook_url:
    type: string
    title: "Notebook URL"
    displayText: "Data Science Notebook: ${notebook_url}"

  bucket_name:
    type: string
    title: "Bucket Name"
    displayText: "Object Storage Bucket: ${bucket_name}"

  agent_endpoint:
    type: string
    title: "GenAI Agent Endpoint"
    displayText: "GenAI Agent: ${agent_endpoint}"